### ISSUE TITLE
jreader needs a NewStreamingReader for io.Reader

### ISSUE THREAD

**Issue by scr-oath** [launchdarkly/go-jsonstream#12]
Similar to NewStreamingWriter, jreader needs to be able to read from an `io.Reader`

**Comment by eli-darkly** [comment]
Hi. Thanks for suggesting this, but it's unlikely that we're going to be adding such a feature in the foreseeable future, for two reasons:
1. LaunchDarkly software doesn't currently need that. This library was created for use in LaunchDarkly products and everything in it is geared toward their needs, so while we say in the readme that it "_may_ be useful in other applications", we're not trying to maintain it as a general-purpose solution and can't prioritize new features. There are other JSON parsing implementations for Go that are much fuller-featured.
2. It would be hard to implement without breaking things about the library that LD software explicitly does need, especially in terms of performance. There are optimizations in the code that rely on the data being in an in-memory buffer.
