### ISSUE TITLE
jreader needs a Raw method that returns []byte

### ISSUE THREAD

**Issue by scr-oath** [launchdarkly/go-jsonstream#13]
Similar to how the jwriter has Raw to write []byte to the stream, there are times when the reader need only know the key and content as raw value (say, to write it out in some other kv store)

In general, jwriter and jreader should offer similar features so one could use one to write and the other to read with the same inputs and outputs.

**Comment by eli-darkly** [comment]
Please see my comment on [your other issue](https://github.com/launchdarkly/go-jsonstream/issues/12).
